// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200704120731_SeedMovies")]
    partial class SeedMovies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorName = "SRK",
                            Title = "DDLJ",
                            Views = 100000000
                        },
                        new
                        {
                            Id = 2,
                            DirectorName = "HR",
                            Title = "ZNMD",
                            Views = 100000000
                        },
                        new
                        {
                            Id = 3,
                            DirectorName = "AK",
                            Title = "3 Idiots",
                            Views = 100000000
                        },
                        new
                        {
                            Id = 4,
                            DirectorName = "PC",
                            Title = "Ishaqzaade",
                            Views = 100000000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
